# Generated by Django 5.1.1 on 2024-09-09 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laporanpemasangan',
            options={'verbose_name': 'Laporan Pemasangan', 'verbose_name_plural': 'Laporan Pemasangan'},
        ),
        migrations.AlterModelOptions(
            name='paketlayanan',
            options={'verbose_name': 'Paket Layanan', 'verbose_name_plural': 'Paket Layanan'},
        ),
        migrations.AlterModelOptions(
            name='pemasanganbaru',
            options={'verbose_name': 'Pemasangan Baru', 'verbose_name_plural': 'Pemasangan Baru'},
        ),
        migrations.AlterModelOptions(
            name='targetbulanan',
            options={'verbose_name': 'Target Bulanan', 'verbose_name_plural': 'Target Bulanan'},
        ),
    ]
