# Generated by Django 5.1.1 on 2024-09-09 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psb', '0002_alter_laporanpemasangan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemasanganbaru',
            name='paket_layanan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='psb.paketlayanan'),
        ),
    ]
