# Generated by Django 5.1.1 on 2024-09-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psb', '0004_alter_pemasanganbaru_paket_layanan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemasanganbaru',
            name='nominal',
        ),
        migrations.AddField(
            model_name='targetbulanan',
            name='jumlah_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='targetbulanan',
            name='target_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='targetbulanan',
            name='current_income',
            field=models.IntegerField(default=0),
        ),
    ]
