# Generated by Django 5.1.1 on 2024-09-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psb', '0005_remove_pemasanganbaru_nominal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pemasanganbaru',
            options={'ordering': ['-tanggal_pasang'], 'verbose_name': 'Pemasangan Baru', 'verbose_name_plural': 'Pemasangan Baru'},
        ),
    ]
