# Generated by Django 5.1.1 on 2024-09-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psb', '0006_alter_pemasanganbaru_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetbulanan',
            name='bulan',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='targetbulanan',
            name='target_user',
            field=models.IntegerField(),
        ),
    ]
