# Generated by Django 5.1.1 on 2024-09-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psb', '0007_alter_targetbulanan_bulan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetbulanan',
            name='target_user',
            field=models.IntegerField(default=0),
        ),
    ]
