# Generated by Django 5.1.1 on 2024-09-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psb', '0009_alter_targetbulanan_target_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetbulanan',
            name='bulan',
            field=models.CharField(max_length=7),
        ),
    ]
