# Generated by Django 5.1.1 on 2024-09-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psb', '0011_alter_targetbulanan_bulan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetbulanan',
            name='bulan',
            field=models.CharField(max_length=7),
        ),
    ]
