# Generated by Django 5.1.1 on 2024-09-11 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psb', '0014_alter_modem_options_alter_teknisi_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modem',
            name='serial_number',
        ),
    ]
