# Generated by Django 5.1.1 on 2024-09-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psb', '0015_remove_modem_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='modem',
            name='serial_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
