# Generated by Django 5.1.1 on 2024-09-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psb', '0016_modem_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemasanganbaru',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
