# Generated by Django 5.1.1 on 2024-09-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psb', '0017_alter_pemasanganbaru_keterangan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelanggan', models.CharField(max_length=100)),
                ('tanggal', models.DateField()),
                ('kode_area', models.CharField(choices=[('A', 'Area A'), ('B', 'Area B')], max_length=50)),
                ('modem', models.CharField(choices=[('Modem1', 'Modem Tipe 1'), ('Modem2', 'Modem Tipe 2')], max_length=100)),
                ('sn_modem', models.CharField(max_length=100)),
                ('teknisi', models.CharField(choices=[('Teknisi1', 'Teknisi 1'), ('Teknisi2', 'Teknisi 2')], max_length=100)),
                ('jenis_kendala', models.CharField(choices=[('Kendala1', 'Kendala Tipe 1'), ('Kendala2', 'Kendala Tipe 2')], max_length=100)),
                ('jenis_perbaikan', models.TextField()),
                ('keterangan_lainnya', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
