# Generated by Django 5.1.1 on 2024-09-12 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psb', '0018_maintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisKendala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kendala', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KodeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('deskripsi', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='modem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psb.modem'),
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='teknisi',
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='jenis_kendala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psb.jeniskendala'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='kode_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psb.kodearea'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='teknisi',
            field=models.ManyToManyField(to='psb.teknisi'),
        ),
    ]
