# Generated by Django 5.1.1 on 2024-09-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psb', '0019_jeniskendala_kodearea_alter_maintenance_modem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kodearea',
            name='kode',
            field=models.CharField(max_length=10),
        ),
    ]
