# Generated by Django 5.1.1 on 2024-09-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psb', '0020_alter_kodearea_kode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='jenis_kendala',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='modem',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='teknisi',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='teknisi',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
