# Generated by Django 5.1.1 on 2024-09-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psb', '0021_alter_maintenance_jenis_kendala_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kodearea',
            old_name='deskripsi',
            new_name='nama',
        ),
    ]
