# Generated by Django 5.1.1 on 2024-09-12 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psb', '0022_rename_deskripsi_kodearea_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='jenis_kendala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psb.jeniskendala'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='modem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='psb.modem'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='teknisi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psb.teknisi'),
        ),
    ]
