# Generated by Django 5.1.1 on 2024-09-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psb', '0023_alter_maintenance_jenis_kendala_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='teknisi',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='teknisi',
            field=models.ManyToManyField(to='psb.teknisi'),
        ),
    ]
